export interface TeamMember {
  name: string
  title: string
  credentials: string
  bio: string
  specialties: string[]
  categories: string[]
  location: string
  initials: string
  imageUrl: string | null
  booking?: string
  notable?: string
  languages?: string[]
  since?: string
  featured?: boolean   // show on homepage
  anchor?: boolean     // featured founder-style card on about page
}

export const TEAM: TeamMember[] = [
  // ─── FOUNDER ────────────────────────────────────────────────────────────────
  {
    name: 'Dr. William Franklin, MD',
    title: 'Founder & Medical Director',
    credentials: 'MD — University of Texas Medical Branch (UTMB), Galveston',
    bio: 'Dr. Franklin has been a healthcare provider since 1983 and founded Victory Medical in 1996 with a vision for integrated care that treats the whole person. He holds specialized training in Natural Hormone Replacement Therapy and Anti-Aging Medicine and serves as associate clinical professor at UT Austin Nursing School.',
    specialties: ['Integrative Medicine', 'Hormone Therapy', 'Anti-Aging', 'Primary Care', 'Addiction Medicine', 'Workers\'s Comp'],
    categories: ['Physicians'],
    location: 'South Austin',
    initials: 'WF',
    imageUrl: '/team/franklin.jpg',
    notable: 'Healthcare provider since 1983 · Founded Victory Medical 1996',
    anchor: true,
    featured: true,
  },

  // ─── PHYSICIANS ─────────────────────────────────────────────────────────────
  {
    name: 'Dr. Michael Armstrong, MD',
    title: 'Family Medicine Physician',
    credentials: 'MD — UT Health McGovern Medical School · Rice University',
    bio: 'Born and raised in Austin. Believes good health involves body, mind, and spirit. Passionate about plants, meditation, and yoga. Fluent in Spanish.',
    specialties: ['Family Medicine', 'Preventive Care', 'Acute Illness'],
    categories: ['Physicians'],
    location: 'South Austin',
    initials: 'MA',
    imageUrl: '/team/armstrong.jpg',
    notable: 'Fluent in Spanish · Austin native',
    languages: ['English', 'Spanish'],
    featured: false,
  },
  {
    name: 'Dr. John Kim, MD',
    title: 'Family Medicine Physician · MDVIP',
    credentials: 'MD — UTMB Galveston · Board-Certified Family Medicine',
    bio: 'Over 23 years with patients. MDVIP-affiliated since 2020. Passionate diagnostician managing complex internal medicine with a focus on preventive care. Named Austin Monthly Best Doctors in 2013.',
    specialties: ['MDVIP Concierge', 'Preventive Medicine', 'Internal Medicine', 'Executive Physical'],
    categories: ['Physicians', 'MDVIP'],
    location: 'Westlake Hills',
    initials: 'JK',
    imageUrl: '/team/john-kim.jpg',
    notable: 'MDVIP affiliated · Austin Monthly Best Doctors 2013',
    featured: false,
  },
  {
    name: 'Dr. Nomita Kim, MD',
    title: 'Family Medicine Physician · MDVIP',
    credentials: 'MD — University of Arkansas for Medical Sciences (UAMS)',
    bio: 'MDVIP-affiliated physician at Westlake Hills. Compassionate and thorough, she prioritizes patient education. Background includes work at an autism clinic.',
    specialties: ['MDVIP Concierge', 'Family Medicine', 'Women\'s Health'],
    categories: ['Physicians', 'MDVIP'],
    location: 'Westlake Hills',
    initials: 'NK',
    imageUrl: '/team/nomita-kim.png',
    notable: 'MDVIP affiliated · Autism clinic background',
    featured: false,
  },
  {
    name: 'Dr. Nathan Henry Pekar, MD',
    title: 'Family Medicine Physician',
    credentials: 'MD — UT Southwestern · Chief Resident, Saint Louis University · Air Force Veteran',
    bio: 'Board-certified family physician with Victory Medical since 2009. Previously served at Little Rock Air Force Base (2004–2009). Specializes in orthopedic injections, dermatology, and vasectomies in addition to comprehensive family medicine.',
    specialties: ['Family Medicine', 'Orthopedic Injections', 'Vasectomies', 'Workers\' Comp', 'Skin Procedures'],
    categories: ['Physicians'],
    location: 'South Austin',
    initials: 'NP',
    imageUrl: '/team/pekar.jpg',
    notable: 'With Victory since 2009 · Air Force veteran · Board-certified',
    since: '2009',
    featured: true,
  },
  {
    name: 'Dr. Sarita H. Prajapati, MD, MPH',
    title: 'Family Medicine Physician',
    credentials: 'MD — UT Southwestern · MPH — UAMS · Diplomat, American Board of Family Medicine',
    bio: 'Named "Top Doctor for 2023." Holds both a medical degree and master\'s in public health. Believes families should be cared for as units, with patient education at the center. Takes a collaborative approach with all practice members.',
    specialties: ['Family Medicine', 'Preventive Care', 'Women\'s Health', 'Chronic Disease'],
    categories: ['Physicians'],
    location: 'Westlake Hills',
    initials: 'SP',
    imageUrl: '/team/prajapati.jpg',
    notable: '"Top Doctor 2023" · MD + MPH',
    featured: false,
  },
  {
    name: 'Gary Albertson, DO',
    title: 'Allergist',
    credentials: 'DO — Kirksville College of Osteopathy and Surgery · 37+ years experience',
    bio: 'Drafted as US Army Battalion Surgeon (1971–1973). After 37 years of family practice — including delivering babies and performing surgery — he now focuses exclusively on allergy care. Moved to Austin in 2005. Owns a Longhorn cattle ranch in Burnet, TX.',
    specialties: ['Allergy Testing', 'Allergy Immunotherapy', 'Asthma', 'Rapid Desensitization'],
    categories: ['Physicians'],
    location: 'Austin · Marble Falls',
    initials: 'GA',
    imageUrl: '/team/albertson.jpg',
    notable: 'Army veteran · 37+ years practice · Allergy specialist',
    featured: false,
  },
  {
    name: 'Dr. Luke Kotin, MD',
    title: 'Family Medicine Physician',
    credentials: 'MD — Texas Tech El Paso · Residency Baylor Scott & White Round Rock',
    bio: 'Grew up in Central Texas. Developed a passion for primary care and lifestyle medicine while working with underserved communities on the Texas border. In his time off, he performs music, records at home, and loves Italian and Indian cooking.',
    specialties: ['Family Medicine', 'Lifestyle Medicine', 'Preventive Care'],
    categories: ['Physicians'],
    location: 'South Austin',
    initials: 'LK',
    imageUrl: '/team/kotin.png',
    notable: 'Musician & composer · Lifestyle medicine focus',
    featured: false,
  },

  // ─── NURSE PRACTITIONERS ────────────────────────────────────────────────────
  {
    name: 'Shawn Agenbroad-Elander, NP',
    title: 'Certified Family Nurse Practitioner',
    credentials: 'MSN-FNP — University of Texas at Austin · RN since 1998',
    bio: 'Believes that collaboration between patient and practitioner is the cornerstone of quality care. Specializes in family medicine, urgent care, and weight loss.',
    specialties: ['Family Medicine', 'Urgent Care', 'Weight Loss'],
    categories: ['Nurse Practitioners'],
    location: 'South Austin',
    initials: 'SA',
    imageUrl: '/team/agenbroad-elander.jpg',
    notable: 'UT Austin NP · RN since 1998',
    featured: false,
  },
  {
    name: 'Melissa Gabrielli, DNP, APRN, FNP-BC, PMHNP-BC',
    title: 'Ketamine Therapist & MedSpa Injector',
    credentials: 'Doctorate in Nursing — University of South Alabama · Dual Board-Certified',
    bio: 'Dual board-certified in family practice and mental health. Background spans pediatric oncology, transplant, and emergency medicine. Has used therapeutic Botox since 2014 and is certified by the American Academy of Facial Esthetics. She serves as consultant for other aesthetically-trained providers.',
    specialties: ['Ketamine Therapy', 'PTSD', 'Depression', 'Botox', 'Dermal Fillers', 'IV Therapy'],
    categories: ['Nurse Practitioners', 'Aesthetics', 'Ketamine & Mental Health'],
    location: 'South Austin / Westlake',
    initials: 'MG',
    imageUrl: '/team/gabrielli-medspa.webp',
    booking: 'https://victory.janeapp.com/',
    notable: 'Dual board-certified (family + mental health)',
    featured: true,
  },
  {
    name: 'Charity Green, APRN',
    title: 'Nurse Practitioner',
    credentials: 'MSN — University of Memphis · Sigma Theta Tau Honor Society',
    bio: 'Started her nursing career in 1996 and has been with Victory Medical since 2016. Known for a gentle bedside manner with patients of all ages. Specializes in allergy assessment and diagnosis.',
    specialties: ['Allergy Assessment', 'Well-Child Visits', 'Pain Management', 'Family Medicine'],
    categories: ['Nurse Practitioners'],
    location: 'South Austin',
    initials: 'CG',
    imageUrl: '/team/green.jpg',
    notable: 'With Victory since 2016 · Sigma Theta Tau honor society',
    since: '2016',
    featured: false,
  },
  {
    name: 'Bailey Johnson-Rae, APRN-CNP',
    title: 'Family Nurse Practitioner',
    credentials: 'BS Nutritional Physiology — Oklahoma State · BS Nursing — UT Health Science Center',
    bio: 'Austin native with a track-and-field scholarship at OSU. Took a path through travel nursing — including rural Alaska — before returning home. Brings sports medicine, EM, and functional medicine expertise. Believes the body is capable of healing with the right support.',
    specialties: ['Functional Medicine', 'Root Cause Medicine', 'Sports Medicine', 'Women\'s Health'],
    categories: ['Nurse Practitioners'],
    location: 'South Austin',
    initials: 'BJ',
    imageUrl: '/team/johnson-rae.png',
    notable: 'Former D1 athlete · Functional & holistic medicine',
    featured: false,
  },
  {
    name: 'Katharine H. Jones, APRN',
    title: 'Nurse Practitioner',
    credentials: 'BSN & MSN — University of Florida · Board-Certified, ANCC',
    bio: 'Former University of Florida Shands Hospital Lung Transplant Team member. Passionate about hormone therapy, sexual health, and aesthetic procedures. Builds strong patient partnerships through a collaborative, whole-person approach.',
    specialties: ['Hormone Therapy', 'Sexual Health', 'Medical Weight Loss', 'Aesthetics', 'Allergy'],
    categories: ['Nurse Practitioners', 'Aesthetics'],
    location: 'South Austin',
    initials: 'KJ',
    imageUrl: '/team/jones.jpg',
    notable: 'UF Shands transplant team · Hormone & aesthetic specialist',
    featured: false,
  },
  {
    name: 'Thao Le, FNP-C',
    title: 'Nurse Practitioner',
    credentials: 'MSN — Western University of Health Sciences · Board-Certified, AANP',
    bio: 'Over 12 years in family medicine and urgent care. Devoted to caring for the whole person with empathy and patience. Passionate about empowering patients to be active participants in their healthcare.',
    specialties: ['Family Medicine', 'Urgent Care', 'Chronic Disease', 'Patient Education'],
    categories: ['Nurse Practitioners'],
    location: 'South Austin',
    initials: 'TL',
    imageUrl: '/team/le.jpg',
    notable: '12+ years family medicine · Speaks Vietnamese',
    languages: ['English', 'Vietnamese'],
    featured: false,
  },
  {
    name: 'Shea Rodriguez, MSN, APRN, FNP-C',
    title: 'Nurse Practitioner · Urgent Care Provider',
    credentials: 'MSN — UTMB Galveston · 19 years nursing before NP',
    bio: 'North Carolina native, Central Texas resident since 1990. Nineteen years of nursing across OBGYN, postpartum, acute care, and neurology before becoming an NP. Whole-patient focus, combining love and compassion with deep clinical experience.',
    specialties: ['Family Medicine', 'Urgent Care', 'Women\'s Health', 'Neurology'],
    categories: ['Nurse Practitioners'],
    location: 'Westlake Hills',
    initials: 'SR',
    imageUrl: '/team/rodriguez.jpg',
    notable: '19 years nursing · UTMB NP',
    featured: false,
  },
  {
    name: 'Jason Spees, APRN-CNP, L.Ac',
    title: 'Nurse Practitioner · Licensed Acupuncturist',
    credentials: 'UT Austin School of Nursing · Licensed Acupuncture & Chinese Medicine',
    bio: 'One of a rare few clinicians holding both NP and Licensed Acupuncturist credentials. Trained in family practice, traditional Chinese medicine, urology, emergency medicine, and chronic pain. Pursuing his PhD in nursing with a research focus on human trafficking.',
    specialties: ['Acupuncture', 'Chinese Medicine', 'Chronic Pain', 'Family Medicine', 'Integrative Care'],
    categories: ['Nurse Practitioners'],
    location: 'South Austin',
    initials: 'JS',
    imageUrl: '/team/spees.jpg',
    notable: 'NP + Licensed Acupuncturist · TCM trained',
    featured: true,
  },
  {
    name: 'Judith "Jude" Chedville, APRN, CNS-BC',
    title: 'Regenerative Medicine Program Director',
    credentials: 'APRN, Board-Certified CNS · Major (Ret.), Texas Army National Guard',
    bio: 'Retired US Army Major and pioneer of Victory Medical\'s Regenerative Medicine program. Specializes in peptide medicine, personalized bioidentical hormone optimization, and ketamine-assisted therapy. Her philosophy is patient-centered, relationship-driven care focused on long-term wellness.',
    specialties: ['Peptide Therapy', 'Regenerative Medicine', 'Bioidentical Hormones', 'Ketamine-Assisted Therapy'],
    categories: ['Nurse Practitioners', 'Ketamine & Mental Health'],
    location: 'South Austin',
    initials: 'JC',
    imageUrl: '/team/chedville.jpg',
    notable: 'Regenerative Medicine Director · Army National Guard (Ret. Major)',
    featured: false,
  },
  {
    name: 'Aleksandra (Ola) Zylka, MSN, FNP-C',
    title: 'Nurse Practitioner & Nurse Injector',
    credentials: 'MSN (4.0 GPA) — Texas Woman\'s University · Neurotoxin Certified',
    bio: 'Originally from Poland, she moved to Austin via travel nursing in 2021. Completed her MSN with a 4.0 GPA. Four-plus years in aesthetics, specializing in injectables, lasers, and advanced facials as a cohesive regimen. Speaks fluent Polish.',
    specialties: ['Botox & Dysport', 'Dermal Fillers', 'Sculptra', 'Laser Treatments', 'Advanced Facials'],
    categories: ['Nurse Practitioners', 'Aesthetics'],
    location: 'South Austin',
    initials: 'OZ',
    imageUrl: '/team/zylka-medspa.jpg',
    booking: 'https://victory.janeapp.com/',
    notable: 'MSN 4.0 GPA · 4+ years aesthetics · Polish speaker',
    languages: ['English', 'Polish'],
    featured: false,
  },

  // ─── PHYSICIAN ASSISTANTS ────────────────────────────────────────────────────
  {
    name: 'Barbara Bolek, PA-C',
    title: 'Certified Physician Assistant',
    credentials: 'MS PA Studies — South College, Knoxville · BS Biology & Professional Health Science',
    bio: 'Practicing as a PA in Central Texas since 2014. Takes a conservative approach with a strong interest in nutrition and healthy lifestyle modifications. CMWL (Medical Weight Loss) certified.',
    specialties: ['Family Medicine', 'Medical Weight Loss', 'Health Screenings', 'Wellness Exams'],
    categories: ['Physician Assistants'],
    location: 'Austin / Westlake Hills',
    initials: 'BB',
    imageUrl: '/team/bolek.jpg',
    notable: 'CMWL certified · Conservative lifestyle medicine',
    featured: false,
  },
  {
    name: 'Maxwell W. Braunstein, PA-C',
    title: 'Board-Certified Physician Assistant',
    credentials: 'MS PA Studies — South University · BS Cellular & Molecular Biology — Christopher Newport University',
    bio: 'Previous roles include urology PA at Urology Austin, Neuroscience ICU at VCU Health, emergency care at HCA Chippenham Hospital, and lab director at GENETWORx. AAPA Leadership & Advocacy Summit nominee (2021).',
    specialties: ['Family Medicine', 'Urgent Care', 'Urology', 'Emergency Medicine'],
    categories: ['Physician Assistants'],
    location: 'South Austin',
    initials: 'MB',
    imageUrl: '/team/braunstein.jpg',
    notable: 'Former urology PA · AAPA leadership',
    featured: false,
  },
  {
    name: 'Ralph M. Hadley, PA',
    title: 'Physician Assistant · Athletic Trainer',
    credentials: 'MS Sports Medicine — Ohio University · PA Certificate — George Washington University',
    bio: 'Has been with Victory Medical since the doors opened in 1996. A dual-credentialed Physician Assistant and Certified Athletic Trainer who spent years treating athletes. Specializes in family practice, orthopedics, sports medicine, and rehabilitation. His patients\' T-shirt motto says it all: "Go See Ralph."',
    specialties: ['Sports Medicine', 'Orthopedics', 'Urgent Care', 'Family Practice', 'Rehabilitation'],
    categories: ['Physician Assistants'],
    location: 'Westlake / South Austin',
    initials: 'RH',
    imageUrl: '/team/hadley.jpg',
    notable: 'With Victory since Day 1, 1996 · Athletic Trainer certified',
    since: '1996',
    featured: true,
  },
  {
    name: 'Laura Nguyen, PA-C',
    title: 'Certified Physician Assistant',
    credentials: 'MS PA Studies — Texas Tech UHSC · Concentration: Nutrition',
    bio: 'Originally from Houston. Worked in family medicine in North Carolina and California before returning to Texas. Seeks root causes, blending conventional and integrative approaches. Speaks Vietnamese and is aspiring to learn Spanish.',
    specialties: ['Family Medicine', 'Hormone Replacement', 'Chronic Disease Management', 'Anti-Aging'],
    categories: ['Physician Assistants'],
    location: 'South Austin',
    initials: 'LN',
    imageUrl: '/team/nguyen-laura.jpg',
    notable: 'Nutrition focus · Speaks Vietnamese',
    languages: ['English', 'Vietnamese'],
    featured: false,
  },
  {
    name: 'Sarah Richter, PA-C',
    title: 'Certified Physician Assistant · Internal Medicine',
    credentials: 'PA — Chatham University · BS — George Washington University · Board-Certified NCCPA',
    bio: 'Background in internal medicine, sleep medicine, and hormone replacement in medically underserved areas of Florida before relocating to Austin. Creates genuine patient bonds and takes a collaborative approach to finding the right health strategy.',
    specialties: ['Internal Medicine', 'Sleep Medicine', 'Hormone Replacement', 'Urgent Care'],
    categories: ['Physician Assistants'],
    location: 'South Austin',
    initials: 'SR2',
    imageUrl: '/team/richter.jpg',
    notable: 'Internal & sleep medicine specialist',
    featured: false,
  },
  {
    name: 'Velia Martinez, PA-C',
    title: 'Certified Physician Assistant · Urgent Care',
    credentials: 'MS PA Studies — Texas Tech University Health Sciences Center',
    bio: 'Originally from El Paso, moved to Austin in 2022. Teaching-focused medicine — believes knowledge empowers patients. No one-size-fits-all approach; she focuses on health optimization and identifying root causes. Speaks fluent Spanish.',
    specialties: ['Urgent Care', 'Family Medicine', 'Women\'s Health', 'Weight Loss'],
    categories: ['Physician Assistants'],
    location: 'South Austin',
    initials: 'VM',
    imageUrl: '/team/martinez.jpg',
    notable: 'Root cause medicine · Speaks Spanish',
    languages: ['English', 'Spanish'],
    featured: false,
  },

  // ─── PHYSICAL MEDICINE ────────────────────────────────────────────────────────
  {
    name: 'Lauren Harmeier, PT, DPT',
    title: 'Licensed Physical Therapist',
    credentials: 'DPT — University of St. Augustine · BS Kinesiology — UT San Antonio',
    bio: 'Doctor of Physical Therapy specializing in chronic pain, neuroscience, sports medicine, and Parkinson\'s Disease therapy. Combines conventional evidence-based methods with individualized treatment for total body wellness.',
    specialties: ['Physical Therapy', 'Chronic Pain', 'Sports Rehab', 'Parkinson\'s Therapy', 'Neuroscience'],
    categories: ['Physical Medicine'],
    location: 'South Austin',
    initials: 'LH',
    imageUrl: '/team/harmeier.jpg',
    notable: 'DPT · Parkinson\'s & chronic pain specialist',
    featured: false,
  },
  {
    name: 'Roy Mullins, DC',
    title: 'Chiropractor',
    credentials: 'Doctor of Chiropractic · Designated Doctor, Workers\' Compensation',
    bio: 'Associate Team Chiropractor for the University of Texas Athletic Program for over 20 years (1991–2013), treating hundreds of college and professional athletes. Works directly alongside physical therapists and physicians for rapid, coordinated results.',
    specialties: ['Chiropractic Care', 'Athletic Injuries', 'Sports Medicine', 'Family Care', 'Workers\' Comp'],
    categories: ['Physical Medicine'],
    location: 'South Austin',
    initials: 'RM',
    imageUrl: '/team/mullins.jpg',
    notable: 'UT Athletic Program chiropractor 1991–2013 · 100s of athletes',
    languages: ['English', 'Spanish'],
    featured: false,
  },

  // ─── SUPPORT PROVIDERS ────────────────────────────────────────────────────────
  {
    name: 'Aaron Zamanian',
    title: 'Pharmacy Director',
    credentials: 'Compounding Pharmacy Specialist',
    bio: 'Director of Victory Medical\'s on-site compounding pharmacy. Oversees custom medication formulations and ensures every compound meets the highest quality and safety standards.',
    specialties: ['Compounding Pharmacy', 'Custom Medications', 'Hormone Compounds', 'Weight Loss Compounds'],
    categories: ['Pharmacy'],
    location: 'South Austin',
    initials: 'AZ',
    imageUrl: '/team/zamanian.jpg',
    notable: 'Pharmacy Director · Compounding specialist',
    featured: false,
  },
  {
    name: 'Lindsey Chagoya',
    title: 'Medical Weight Loss Director',
    credentials: 'CMWL Certified Medical Weight Loss Director',
    bio: 'Certified Medical Weight Loss director overseeing Victory Medical\'s comprehensive weight loss programs. Expert in personalized nutrition, metabolic health, and sustainable lifestyle transformation.',
    specialties: ['Medical Weight Loss', 'Nutrition', 'Metabolic Health', 'Lifestyle Coaching'],
    categories: ['Pharmacy'],
    location: 'South Austin',
    initials: 'LC',
    imageUrl: '/team/chagoya.jpg',
    notable: 'CMWL certified · Weight loss program director',
    featured: false,
  },
]

export const FEATURED_TEAM = TEAM.filter(m => m.featured)
export const FOUNDER = TEAM.find(m => m.anchor)
export const FILTER_CATEGORIES = [
  'All',
  'Physicians',
  'Nurse Practitioners',
  'Physician Assistants',
  'Aesthetics',
  'Ketamine & Mental Health',
  'Physical Medicine',
  'MDVIP',
  'Pharmacy',
]
